// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LowerLevelHashes.proto

#ifndef PROTOBUF_LowerLevelHashes_2eproto__INCLUDED
#define PROTOBUF_LowerLevelHashes_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace quadtreesync {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_LowerLevelHashes_2eproto();
void protobuf_AssignDesc_LowerLevelHashes_2eproto();
void protobuf_ShutdownFile_LowerLevelHashes_2eproto();

class HashValueList;
class LowerLevelHashes;

// ===================================================================

class LowerLevelHashes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:quadtreesync.LowerLevelHashes) */ {
 public:
  LowerLevelHashes();
  virtual ~LowerLevelHashes();

  LowerLevelHashes(const LowerLevelHashes& from);

  inline LowerLevelHashes& operator=(const LowerLevelHashes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LowerLevelHashes& default_instance();

  void Swap(LowerLevelHashes* other);

  // implements Message ----------------------------------------------

  inline LowerLevelHashes* New() const { return New(NULL); }

  LowerLevelHashes* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LowerLevelHashes& from);
  void MergeFrom(const LowerLevelHashes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LowerLevelHashes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 numChanges = 1;
  bool has_numchanges() const;
  void clear_numchanges();
  static const int kNumChangesFieldNumber = 1;
  ::google::protobuf::uint64 numchanges() const;
  void set_numchanges(::google::protobuf::uint64 value);

  // required uint64 treeLevel = 2;
  bool has_treelevel() const;
  void clear_treelevel();
  static const int kTreeLevelFieldNumber = 2;
  ::google::protobuf::uint64 treelevel() const;
  void set_treelevel(::google::protobuf::uint64 value);

  // required .quadtreesync.HashValueList hashValues = 3;
  bool has_hashvalues() const;
  void clear_hashvalues();
  static const int kHashValuesFieldNumber = 3;
  const ::quadtreesync::HashValueList& hashvalues() const;
  ::quadtreesync::HashValueList* mutable_hashvalues();
  ::quadtreesync::HashValueList* release_hashvalues();
  void set_allocated_hashvalues(::quadtreesync::HashValueList* hashvalues);

  // @@protoc_insertion_point(class_scope:quadtreesync.LowerLevelHashes)
 private:
  inline void set_has_numchanges();
  inline void clear_has_numchanges();
  inline void set_has_treelevel();
  inline void clear_has_treelevel();
  inline void set_has_hashvalues();
  inline void clear_has_hashvalues();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 numchanges_;
  ::google::protobuf::uint64 treelevel_;
  ::quadtreesync::HashValueList* hashvalues_;
  friend void  protobuf_AddDesc_LowerLevelHashes_2eproto();
  friend void protobuf_AssignDesc_LowerLevelHashes_2eproto();
  friend void protobuf_ShutdownFile_LowerLevelHashes_2eproto();

  void InitAsDefaultInstance();
  static LowerLevelHashes* default_instance_;
};
// -------------------------------------------------------------------

class HashValueList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:quadtreesync.HashValueList) */ {
 public:
  HashValueList();
  virtual ~HashValueList();

  HashValueList(const HashValueList& from);

  inline HashValueList& operator=(const HashValueList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HashValueList& default_instance();

  void Swap(HashValueList* other);

  // implements Message ----------------------------------------------

  inline HashValueList* New() const { return New(NULL); }

  HashValueList* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HashValueList& from);
  void MergeFrom(const HashValueList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HashValueList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 hashValues = 3;
  int hashvalues_size() const;
  void clear_hashvalues();
  static const int kHashValuesFieldNumber = 3;
  ::google::protobuf::uint64 hashvalues(int index) const;
  void set_hashvalues(int index, ::google::protobuf::uint64 value);
  void add_hashvalues(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      hashvalues() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_hashvalues();

  // @@protoc_insertion_point(class_scope:quadtreesync.HashValueList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > hashvalues_;
  friend void  protobuf_AddDesc_LowerLevelHashes_2eproto();
  friend void protobuf_AssignDesc_LowerLevelHashes_2eproto();
  friend void protobuf_ShutdownFile_LowerLevelHashes_2eproto();

  void InitAsDefaultInstance();
  static HashValueList* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LowerLevelHashes

// required uint64 numChanges = 1;
inline bool LowerLevelHashes::has_numchanges() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LowerLevelHashes::set_has_numchanges() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LowerLevelHashes::clear_has_numchanges() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LowerLevelHashes::clear_numchanges() {
  numchanges_ = GOOGLE_ULONGLONG(0);
  clear_has_numchanges();
}
inline ::google::protobuf::uint64 LowerLevelHashes::numchanges() const {
  // @@protoc_insertion_point(field_get:quadtreesync.LowerLevelHashes.numChanges)
  return numchanges_;
}
inline void LowerLevelHashes::set_numchanges(::google::protobuf::uint64 value) {
  set_has_numchanges();
  numchanges_ = value;
  // @@protoc_insertion_point(field_set:quadtreesync.LowerLevelHashes.numChanges)
}

// required uint64 treeLevel = 2;
inline bool LowerLevelHashes::has_treelevel() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LowerLevelHashes::set_has_treelevel() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LowerLevelHashes::clear_has_treelevel() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LowerLevelHashes::clear_treelevel() {
  treelevel_ = GOOGLE_ULONGLONG(0);
  clear_has_treelevel();
}
inline ::google::protobuf::uint64 LowerLevelHashes::treelevel() const {
  // @@protoc_insertion_point(field_get:quadtreesync.LowerLevelHashes.treeLevel)
  return treelevel_;
}
inline void LowerLevelHashes::set_treelevel(::google::protobuf::uint64 value) {
  set_has_treelevel();
  treelevel_ = value;
  // @@protoc_insertion_point(field_set:quadtreesync.LowerLevelHashes.treeLevel)
}

// required .quadtreesync.HashValueList hashValues = 3;
inline bool LowerLevelHashes::has_hashvalues() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LowerLevelHashes::set_has_hashvalues() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LowerLevelHashes::clear_has_hashvalues() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LowerLevelHashes::clear_hashvalues() {
  if (hashvalues_ != NULL) hashvalues_->::quadtreesync::HashValueList::Clear();
  clear_has_hashvalues();
}
inline const ::quadtreesync::HashValueList& LowerLevelHashes::hashvalues() const {
  // @@protoc_insertion_point(field_get:quadtreesync.LowerLevelHashes.hashValues)
  return hashvalues_ != NULL ? *hashvalues_ : *default_instance_->hashvalues_;
}
inline ::quadtreesync::HashValueList* LowerLevelHashes::mutable_hashvalues() {
  set_has_hashvalues();
  if (hashvalues_ == NULL) {
    hashvalues_ = new ::quadtreesync::HashValueList;
  }
  // @@protoc_insertion_point(field_mutable:quadtreesync.LowerLevelHashes.hashValues)
  return hashvalues_;
}
inline ::quadtreesync::HashValueList* LowerLevelHashes::release_hashvalues() {
  // @@protoc_insertion_point(field_release:quadtreesync.LowerLevelHashes.hashValues)
  clear_has_hashvalues();
  ::quadtreesync::HashValueList* temp = hashvalues_;
  hashvalues_ = NULL;
  return temp;
}
inline void LowerLevelHashes::set_allocated_hashvalues(::quadtreesync::HashValueList* hashvalues) {
  delete hashvalues_;
  hashvalues_ = hashvalues;
  if (hashvalues) {
    set_has_hashvalues();
  } else {
    clear_has_hashvalues();
  }
  // @@protoc_insertion_point(field_set_allocated:quadtreesync.LowerLevelHashes.hashValues)
}

// -------------------------------------------------------------------

// HashValueList

// repeated uint64 hashValues = 3;
inline int HashValueList::hashvalues_size() const {
  return hashvalues_.size();
}
inline void HashValueList::clear_hashvalues() {
  hashvalues_.Clear();
}
inline ::google::protobuf::uint64 HashValueList::hashvalues(int index) const {
  // @@protoc_insertion_point(field_get:quadtreesync.HashValueList.hashValues)
  return hashvalues_.Get(index);
}
inline void HashValueList::set_hashvalues(int index, ::google::protobuf::uint64 value) {
  hashvalues_.Set(index, value);
  // @@protoc_insertion_point(field_set:quadtreesync.HashValueList.hashValues)
}
inline void HashValueList::add_hashvalues(::google::protobuf::uint64 value) {
  hashvalues_.Add(value);
  // @@protoc_insertion_point(field_add:quadtreesync.HashValueList.hashValues)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
HashValueList::hashvalues() const {
  // @@protoc_insertion_point(field_list:quadtreesync.HashValueList.hashValues)
  return hashvalues_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
HashValueList::mutable_hashvalues() {
  // @@protoc_insertion_point(field_mutable_list:quadtreesync.HashValueList.hashValues)
  return &hashvalues_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace quadtreesync

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_LowerLevelHashes_2eproto__INCLUDED
