// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SyncResponse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SyncResponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace quadtree {

namespace {

const ::google::protobuf::Descriptor* SyncResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SyncResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* ChunkData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ChunkData_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_SyncResponse_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_SyncResponse_2eproto() {
  protobuf_AddDesc_SyncResponse_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SyncResponse.proto");
  GOOGLE_CHECK(file != NULL);
  SyncResponse_descriptor_ = file->message_type(0);
  static const int SyncResponse_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SyncResponse, hashknown_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SyncResponse, chunkdata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SyncResponse, curhash_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SyncResponse, lastpublishevent_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SyncResponse, chunks_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SyncResponse, treelevel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SyncResponse, hashvalues_),
  };
  SyncResponse_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SyncResponse_descriptor_,
      SyncResponse::default_instance_,
      SyncResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SyncResponse, _has_bits_[0]),
      -1,
      -1,
      sizeof(SyncResponse),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SyncResponse, _internal_metadata_),
      -1);
  ChunkData_descriptor_ = file->message_type(1);
  static const int ChunkData_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChunkData, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChunkData, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChunkData, data_),
  };
  ChunkData_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ChunkData_descriptor_,
      ChunkData::default_instance_,
      ChunkData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChunkData, _has_bits_[0]),
      -1,
      -1,
      sizeof(ChunkData),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChunkData, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SyncResponse_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SyncResponse_descriptor_, &SyncResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ChunkData_descriptor_, &ChunkData::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SyncResponse_2eproto() {
  delete SyncResponse::default_instance_;
  delete SyncResponse_reflection_;
  delete ChunkData::default_instance_;
  delete ChunkData_reflection_;
}

void protobuf_AddDesc_SyncResponse_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_SyncResponse_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022SyncResponse.proto\022\010quadtree\"\253\001\n\014SyncR"
    "esponse\022\021\n\thashKnown\030\001 \002(\010\022\021\n\tchunkData\030"
    "\002 \002(\010\022\017\n\007curHash\030\003 \002(\004\022\030\n\020lastPublishEve"
    "nt\030\007 \002(\003\022#\n\006chunks\030\004 \003(\0132\023.quadtree.Chun"
    "kData\022\021\n\ttreeLevel\030\005 \001(\r\022\022\n\nhashValues\030\006"
    " \003(\004\"/\n\tChunkData\022\t\n\001x\030\001 \002(\004\022\t\n\001y\030\002 \002(\004\022"
    "\014\n\004data\030\003 \002(\004", 253);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SyncResponse.proto", &protobuf_RegisterTypes);
  SyncResponse::default_instance_ = new SyncResponse();
  ChunkData::default_instance_ = new ChunkData();
  SyncResponse::default_instance_->InitAsDefaultInstance();
  ChunkData::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SyncResponse_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SyncResponse_2eproto {
  StaticDescriptorInitializer_SyncResponse_2eproto() {
    protobuf_AddDesc_SyncResponse_2eproto();
  }
} static_descriptor_initializer_SyncResponse_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SyncResponse::kHashKnownFieldNumber;
const int SyncResponse::kChunkDataFieldNumber;
const int SyncResponse::kCurHashFieldNumber;
const int SyncResponse::kLastPublishEventFieldNumber;
const int SyncResponse::kChunksFieldNumber;
const int SyncResponse::kTreeLevelFieldNumber;
const int SyncResponse::kHashValuesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SyncResponse::SyncResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:quadtree.SyncResponse)
}

void SyncResponse::InitAsDefaultInstance() {
}

SyncResponse::SyncResponse(const SyncResponse& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:quadtree.SyncResponse)
}

void SyncResponse::SharedCtor() {
  _cached_size_ = 0;
  hashknown_ = false;
  chunkdata_ = false;
  curhash_ = GOOGLE_ULONGLONG(0);
  lastpublishevent_ = GOOGLE_LONGLONG(0);
  treelevel_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SyncResponse::~SyncResponse() {
  // @@protoc_insertion_point(destructor:quadtree.SyncResponse)
  SharedDtor();
}

void SyncResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SyncResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SyncResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SyncResponse_descriptor_;
}

const SyncResponse& SyncResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SyncResponse_2eproto();
  return *default_instance_;
}

SyncResponse* SyncResponse::default_instance_ = NULL;

SyncResponse* SyncResponse::New(::google::protobuf::Arena* arena) const {
  SyncResponse* n = new SyncResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SyncResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:quadtree.SyncResponse)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(SyncResponse, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<SyncResponse*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 47u) {
    ZR_(curhash_, lastpublishevent_);
  }

#undef ZR_HELPER_
#undef ZR_

  chunks_.Clear();
  hashvalues_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool SyncResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:quadtree.SyncResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool hashKnown = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &hashknown_)));
          set_has_hashknown();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_chunkData;
        break;
      }

      // required bool chunkData = 2;
      case 2: {
        if (tag == 16) {
         parse_chunkData:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &chunkdata_)));
          set_has_chunkdata();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_curHash;
        break;
      }

      // required uint64 curHash = 3;
      case 3: {
        if (tag == 24) {
         parse_curHash:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &curhash_)));
          set_has_curhash();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_chunks;
        break;
      }

      // repeated .quadtree.ChunkData chunks = 4;
      case 4: {
        if (tag == 34) {
         parse_chunks:
          DO_(input->IncrementRecursionDepth());
         parse_loop_chunks:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_chunks()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_loop_chunks;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(40)) goto parse_treeLevel;
        break;
      }

      // optional uint32 treeLevel = 5;
      case 5: {
        if (tag == 40) {
         parse_treeLevel:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &treelevel_)));
          set_has_treelevel();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_hashValues;
        break;
      }

      // repeated uint64 hashValues = 6;
      case 6: {
        if (tag == 48) {
         parse_hashValues:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 48, input, this->mutable_hashvalues())));
        } else if (tag == 50) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_hashvalues())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_hashValues;
        if (input->ExpectTag(56)) goto parse_lastPublishEvent;
        break;
      }

      // required int64 lastPublishEvent = 7;
      case 7: {
        if (tag == 56) {
         parse_lastPublishEvent:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &lastpublishevent_)));
          set_has_lastpublishevent();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:quadtree.SyncResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:quadtree.SyncResponse)
  return false;
#undef DO_
}

void SyncResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:quadtree.SyncResponse)
  // required bool hashKnown = 1;
  if (has_hashknown()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->hashknown(), output);
  }

  // required bool chunkData = 2;
  if (has_chunkdata()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->chunkdata(), output);
  }

  // required uint64 curHash = 3;
  if (has_curhash()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->curhash(), output);
  }

  // repeated .quadtree.ChunkData chunks = 4;
  for (unsigned int i = 0, n = this->chunks_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->chunks(i), output);
  }

  // optional uint32 treeLevel = 5;
  if (has_treelevel()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->treelevel(), output);
  }

  // repeated uint64 hashValues = 6;
  for (int i = 0; i < this->hashvalues_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      6, this->hashvalues(i), output);
  }

  // required int64 lastPublishEvent = 7;
  if (has_lastpublishevent()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(7, this->lastpublishevent(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:quadtree.SyncResponse)
}

::google::protobuf::uint8* SyncResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:quadtree.SyncResponse)
  // required bool hashKnown = 1;
  if (has_hashknown()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->hashknown(), target);
  }

  // required bool chunkData = 2;
  if (has_chunkdata()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->chunkdata(), target);
  }

  // required uint64 curHash = 3;
  if (has_curhash()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->curhash(), target);
  }

  // repeated .quadtree.ChunkData chunks = 4;
  for (unsigned int i = 0, n = this->chunks_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, this->chunks(i), false, target);
  }

  // optional uint32 treeLevel = 5;
  if (has_treelevel()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->treelevel(), target);
  }

  // repeated uint64 hashValues = 6;
  for (int i = 0; i < this->hashvalues_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(6, this->hashvalues(i), target);
  }

  // required int64 lastPublishEvent = 7;
  if (has_lastpublishevent()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(7, this->lastpublishevent(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:quadtree.SyncResponse)
  return target;
}

int SyncResponse::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:quadtree.SyncResponse)
  int total_size = 0;

  if (has_hashknown()) {
    // required bool hashKnown = 1;
    total_size += 1 + 1;
  }

  if (has_chunkdata()) {
    // required bool chunkData = 2;
    total_size += 1 + 1;
  }

  if (has_curhash()) {
    // required uint64 curHash = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->curhash());
  }

  if (has_lastpublishevent()) {
    // required int64 lastPublishEvent = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->lastpublishevent());
  }

  return total_size;
}
int SyncResponse::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:quadtree.SyncResponse)
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required bool hashKnown = 1;
    total_size += 1 + 1;

    // required bool chunkData = 2;
    total_size += 1 + 1;

    // required uint64 curHash = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->curhash());

    // required int64 lastPublishEvent = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->lastpublishevent());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional uint32 treeLevel = 5;
  if (has_treelevel()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->treelevel());
  }

  // repeated .quadtree.ChunkData chunks = 4;
  total_size += 1 * this->chunks_size();
  for (int i = 0; i < this->chunks_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->chunks(i));
  }

  // repeated uint64 hashValues = 6;
  {
    int data_size = 0;
    for (int i = 0; i < this->hashvalues_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->hashvalues(i));
    }
    total_size += 1 * this->hashvalues_size() + data_size;
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SyncResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:quadtree.SyncResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const SyncResponse* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SyncResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:quadtree.SyncResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:quadtree.SyncResponse)
    MergeFrom(*source);
  }
}

void SyncResponse::MergeFrom(const SyncResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:quadtree.SyncResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  chunks_.MergeFrom(from.chunks_);
  hashvalues_.MergeFrom(from.hashvalues_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_hashknown()) {
      set_hashknown(from.hashknown());
    }
    if (from.has_chunkdata()) {
      set_chunkdata(from.chunkdata());
    }
    if (from.has_curhash()) {
      set_curhash(from.curhash());
    }
    if (from.has_lastpublishevent()) {
      set_lastpublishevent(from.lastpublishevent());
    }
    if (from.has_treelevel()) {
      set_treelevel(from.treelevel());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void SyncResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:quadtree.SyncResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SyncResponse::CopyFrom(const SyncResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:quadtree.SyncResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SyncResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->chunks())) return false;
  return true;
}

void SyncResponse::Swap(SyncResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SyncResponse::InternalSwap(SyncResponse* other) {
  std::swap(hashknown_, other->hashknown_);
  std::swap(chunkdata_, other->chunkdata_);
  std::swap(curhash_, other->curhash_);
  std::swap(lastpublishevent_, other->lastpublishevent_);
  chunks_.UnsafeArenaSwap(&other->chunks_);
  std::swap(treelevel_, other->treelevel_);
  hashvalues_.UnsafeArenaSwap(&other->hashvalues_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SyncResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SyncResponse_descriptor_;
  metadata.reflection = SyncResponse_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SyncResponse

// required bool hashKnown = 1;
bool SyncResponse::has_hashknown() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void SyncResponse::set_has_hashknown() {
  _has_bits_[0] |= 0x00000001u;
}
void SyncResponse::clear_has_hashknown() {
  _has_bits_[0] &= ~0x00000001u;
}
void SyncResponse::clear_hashknown() {
  hashknown_ = false;
  clear_has_hashknown();
}
 bool SyncResponse::hashknown() const {
  // @@protoc_insertion_point(field_get:quadtree.SyncResponse.hashKnown)
  return hashknown_;
}
 void SyncResponse::set_hashknown(bool value) {
  set_has_hashknown();
  hashknown_ = value;
  // @@protoc_insertion_point(field_set:quadtree.SyncResponse.hashKnown)
}

// required bool chunkData = 2;
bool SyncResponse::has_chunkdata() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void SyncResponse::set_has_chunkdata() {
  _has_bits_[0] |= 0x00000002u;
}
void SyncResponse::clear_has_chunkdata() {
  _has_bits_[0] &= ~0x00000002u;
}
void SyncResponse::clear_chunkdata() {
  chunkdata_ = false;
  clear_has_chunkdata();
}
 bool SyncResponse::chunkdata() const {
  // @@protoc_insertion_point(field_get:quadtree.SyncResponse.chunkData)
  return chunkdata_;
}
 void SyncResponse::set_chunkdata(bool value) {
  set_has_chunkdata();
  chunkdata_ = value;
  // @@protoc_insertion_point(field_set:quadtree.SyncResponse.chunkData)
}

// required uint64 curHash = 3;
bool SyncResponse::has_curhash() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void SyncResponse::set_has_curhash() {
  _has_bits_[0] |= 0x00000004u;
}
void SyncResponse::clear_has_curhash() {
  _has_bits_[0] &= ~0x00000004u;
}
void SyncResponse::clear_curhash() {
  curhash_ = GOOGLE_ULONGLONG(0);
  clear_has_curhash();
}
 ::google::protobuf::uint64 SyncResponse::curhash() const {
  // @@protoc_insertion_point(field_get:quadtree.SyncResponse.curHash)
  return curhash_;
}
 void SyncResponse::set_curhash(::google::protobuf::uint64 value) {
  set_has_curhash();
  curhash_ = value;
  // @@protoc_insertion_point(field_set:quadtree.SyncResponse.curHash)
}

// required int64 lastPublishEvent = 7;
bool SyncResponse::has_lastpublishevent() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void SyncResponse::set_has_lastpublishevent() {
  _has_bits_[0] |= 0x00000008u;
}
void SyncResponse::clear_has_lastpublishevent() {
  _has_bits_[0] &= ~0x00000008u;
}
void SyncResponse::clear_lastpublishevent() {
  lastpublishevent_ = GOOGLE_LONGLONG(0);
  clear_has_lastpublishevent();
}
 ::google::protobuf::int64 SyncResponse::lastpublishevent() const {
  // @@protoc_insertion_point(field_get:quadtree.SyncResponse.lastPublishEvent)
  return lastpublishevent_;
}
 void SyncResponse::set_lastpublishevent(::google::protobuf::int64 value) {
  set_has_lastpublishevent();
  lastpublishevent_ = value;
  // @@protoc_insertion_point(field_set:quadtree.SyncResponse.lastPublishEvent)
}

// repeated .quadtree.ChunkData chunks = 4;
int SyncResponse::chunks_size() const {
  return chunks_.size();
}
void SyncResponse::clear_chunks() {
  chunks_.Clear();
}
const ::quadtree::ChunkData& SyncResponse::chunks(int index) const {
  // @@protoc_insertion_point(field_get:quadtree.SyncResponse.chunks)
  return chunks_.Get(index);
}
::quadtree::ChunkData* SyncResponse::mutable_chunks(int index) {
  // @@protoc_insertion_point(field_mutable:quadtree.SyncResponse.chunks)
  return chunks_.Mutable(index);
}
::quadtree::ChunkData* SyncResponse::add_chunks() {
  // @@protoc_insertion_point(field_add:quadtree.SyncResponse.chunks)
  return chunks_.Add();
}
::google::protobuf::RepeatedPtrField< ::quadtree::ChunkData >*
SyncResponse::mutable_chunks() {
  // @@protoc_insertion_point(field_mutable_list:quadtree.SyncResponse.chunks)
  return &chunks_;
}
const ::google::protobuf::RepeatedPtrField< ::quadtree::ChunkData >&
SyncResponse::chunks() const {
  // @@protoc_insertion_point(field_list:quadtree.SyncResponse.chunks)
  return chunks_;
}

// optional uint32 treeLevel = 5;
bool SyncResponse::has_treelevel() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void SyncResponse::set_has_treelevel() {
  _has_bits_[0] |= 0x00000020u;
}
void SyncResponse::clear_has_treelevel() {
  _has_bits_[0] &= ~0x00000020u;
}
void SyncResponse::clear_treelevel() {
  treelevel_ = 0u;
  clear_has_treelevel();
}
 ::google::protobuf::uint32 SyncResponse::treelevel() const {
  // @@protoc_insertion_point(field_get:quadtree.SyncResponse.treeLevel)
  return treelevel_;
}
 void SyncResponse::set_treelevel(::google::protobuf::uint32 value) {
  set_has_treelevel();
  treelevel_ = value;
  // @@protoc_insertion_point(field_set:quadtree.SyncResponse.treeLevel)
}

// repeated uint64 hashValues = 6;
int SyncResponse::hashvalues_size() const {
  return hashvalues_.size();
}
void SyncResponse::clear_hashvalues() {
  hashvalues_.Clear();
}
 ::google::protobuf::uint64 SyncResponse::hashvalues(int index) const {
  // @@protoc_insertion_point(field_get:quadtree.SyncResponse.hashValues)
  return hashvalues_.Get(index);
}
 void SyncResponse::set_hashvalues(int index, ::google::protobuf::uint64 value) {
  hashvalues_.Set(index, value);
  // @@protoc_insertion_point(field_set:quadtree.SyncResponse.hashValues)
}
 void SyncResponse::add_hashvalues(::google::protobuf::uint64 value) {
  hashvalues_.Add(value);
  // @@protoc_insertion_point(field_add:quadtree.SyncResponse.hashValues)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
SyncResponse::hashvalues() const {
  // @@protoc_insertion_point(field_list:quadtree.SyncResponse.hashValues)
  return hashvalues_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
SyncResponse::mutable_hashvalues() {
  // @@protoc_insertion_point(field_mutable_list:quadtree.SyncResponse.hashValues)
  return &hashvalues_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ChunkData::kXFieldNumber;
const int ChunkData::kYFieldNumber;
const int ChunkData::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ChunkData::ChunkData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:quadtree.ChunkData)
}

void ChunkData::InitAsDefaultInstance() {
}

ChunkData::ChunkData(const ChunkData& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:quadtree.ChunkData)
}

void ChunkData::SharedCtor() {
  _cached_size_ = 0;
  x_ = GOOGLE_ULONGLONG(0);
  y_ = GOOGLE_ULONGLONG(0);
  data_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ChunkData::~ChunkData() {
  // @@protoc_insertion_point(destructor:quadtree.ChunkData)
  SharedDtor();
}

void ChunkData::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ChunkData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ChunkData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ChunkData_descriptor_;
}

const ChunkData& ChunkData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SyncResponse_2eproto();
  return *default_instance_;
}

ChunkData* ChunkData::default_instance_ = NULL;

ChunkData* ChunkData::New(::google::protobuf::Arena* arena) const {
  ChunkData* n = new ChunkData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ChunkData::Clear() {
// @@protoc_insertion_point(message_clear_start:quadtree.ChunkData)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(ChunkData, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<ChunkData*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(x_, data_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool ChunkData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:quadtree.ChunkData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 x = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_y;
        break;
      }

      // required uint64 y = 2;
      case 2: {
        if (tag == 16) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_data;
        break;
      }

      // required uint64 data = 3;
      case 3: {
        if (tag == 24) {
         parse_data:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &data_)));
          set_has_data();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:quadtree.ChunkData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:quadtree.ChunkData)
  return false;
#undef DO_
}

void ChunkData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:quadtree.ChunkData)
  // required uint64 x = 1;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->x(), output);
  }

  // required uint64 y = 2;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->y(), output);
  }

  // required uint64 data = 3;
  if (has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->data(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:quadtree.ChunkData)
}

::google::protobuf::uint8* ChunkData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:quadtree.ChunkData)
  // required uint64 x = 1;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->x(), target);
  }

  // required uint64 y = 2;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->y(), target);
  }

  // required uint64 data = 3;
  if (has_data()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->data(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:quadtree.ChunkData)
  return target;
}

int ChunkData::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:quadtree.ChunkData)
  int total_size = 0;

  if (has_x()) {
    // required uint64 x = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->x());
  }

  if (has_y()) {
    // required uint64 y = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->y());
  }

  if (has_data()) {
    // required uint64 data = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->data());
  }

  return total_size;
}
int ChunkData::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:quadtree.ChunkData)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required uint64 x = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->x());

    // required uint64 y = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->y());

    // required uint64 data = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->data());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ChunkData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:quadtree.ChunkData)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ChunkData* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ChunkData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:quadtree.ChunkData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:quadtree.ChunkData)
    MergeFrom(*source);
  }
}

void ChunkData::MergeFrom(const ChunkData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:quadtree.ChunkData)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
    if (from.has_data()) {
      set_data(from.data());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void ChunkData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:quadtree.ChunkData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ChunkData::CopyFrom(const ChunkData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:quadtree.ChunkData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChunkData::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void ChunkData::Swap(ChunkData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ChunkData::InternalSwap(ChunkData* other) {
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(data_, other->data_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ChunkData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ChunkData_descriptor_;
  metadata.reflection = ChunkData_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ChunkData

// required uint64 x = 1;
bool ChunkData::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ChunkData::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
void ChunkData::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
void ChunkData::clear_x() {
  x_ = GOOGLE_ULONGLONG(0);
  clear_has_x();
}
 ::google::protobuf::uint64 ChunkData::x() const {
  // @@protoc_insertion_point(field_get:quadtree.ChunkData.x)
  return x_;
}
 void ChunkData::set_x(::google::protobuf::uint64 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:quadtree.ChunkData.x)
}

// required uint64 y = 2;
bool ChunkData::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void ChunkData::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
void ChunkData::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
void ChunkData::clear_y() {
  y_ = GOOGLE_ULONGLONG(0);
  clear_has_y();
}
 ::google::protobuf::uint64 ChunkData::y() const {
  // @@protoc_insertion_point(field_get:quadtree.ChunkData.y)
  return y_;
}
 void ChunkData::set_y(::google::protobuf::uint64 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:quadtree.ChunkData.y)
}

// required uint64 data = 3;
bool ChunkData::has_data() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void ChunkData::set_has_data() {
  _has_bits_[0] |= 0x00000004u;
}
void ChunkData::clear_has_data() {
  _has_bits_[0] &= ~0x00000004u;
}
void ChunkData::clear_data() {
  data_ = GOOGLE_ULONGLONG(0);
  clear_has_data();
}
 ::google::protobuf::uint64 ChunkData::data() const {
  // @@protoc_insertion_point(field_get:quadtree.ChunkData.data)
  return data_;
}
 void ChunkData::set_data(::google::protobuf::uint64 value) {
  set_has_data();
  data_ = value;
  // @@protoc_insertion_point(field_set:quadtree.ChunkData.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace quadtree

// @@protoc_insertion_point(global_scope)
